import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const demo = path.join(root, "public", "demo");
const html = fs.readFileSync(path.join(demo, "index.html"), "utf8");
const ui = fs.readFileSync(path.join(demo, "watchalong-canon-ui.js"), "utf8");
const css = fs.readFileSync(path.join(demo, "watchalong-canon.css"), "utf8");
const app = fs.readFileSync(path.join(demo, "app.js"), "utf8");
const dossierCss = fs.readFileSync(path.join(demo, "source-dossier.css"), "utf8");
const context = { console };
context.window = context;
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(demo, "wwam-watchalong-canon.js"), "utf8"), context);
vm.runInContext(fs.readFileSync(path.join(demo, "wwam-watchalong-route-index.js"), "utf8"), context);
vm.runInContext(fs.readFileSync(path.join(demo, "wwam-watch-pass-pilot.js"), "utf8"), context);
vm.runInContext(fs.readFileSync(path.join(demo, "wwam-podcast-commentary-audio.js"), "utf8"), context);
const canon = context.WWAM_WATCHALONG_CANON;
const routeIndex = context.WWAM_WATCHALONG_ROUTE_INDEX;
const watchPass = context.WWAM_WATCH_PASS_PILOT;
const podcastAudio = context.WWAM_PODCAST_COMMENTARY_AUDIO;

test("cold-route Show Wiki index mirrors every source and keeps full dossier cuts", () => {
  assert.equal(routeIndex.schema, "shokker-wwam-watchalong-route-index/v1");
  assert.equal(routeIndex.sources.length, 130);
  const halloweenFour = routeIndex.sources.find((source) => source.id === "28PfRNKoSCA");
  assert.ok(halloweenFour);
  assert.equal(halloweenFour.dossier.cuts.length, 37);
  assert.ok(halloweenFour.dossier.cuts.some((cut) => cut.category === "STRAIGHT TO STEVE'S ASSHOLE"));
  const heldH2 = routeIndex.sources.find((source) => source.id === "AzrcgoyE7C4");
  assert.ok(heldH2?.alternateAudio, "held H2 keeps its official podcast edition on the cold route");
  assert.equal(heldH2.alternateAudio.candidateCount, 43);
  assert.equal(heldH2.alternateAudio.timestampIsomorphic, false);
  assert.equal(heldH2.alternateAudio.routes.length, 43);
  assert.match(heldH2.alternateAudio.enclosureUrl, /^https:\/\/traffic\.megaphone\.fm\//);
  assert.ok(heldH2.alternateAudio.routes.every((route) => route.clock === "official WWAM podcast clock"));
});

test("watchalong canon has the complete public source registry", () => {
  assert.equal(canon.schema, "shokker-wwam-watchalong-canon/v1");
  assert.match(canon.sourcePolicy, /non-isomorphic/i);
  assert.equal(canon.podcastAudit.feedItemsAudited, 56);
  assert.equal(canon.podcastAudit.titleExplicitFilmCommentaries, 56);
  assert.equal(canon.podcastAudit.newToPublicYouTubeCanon, 6);
  assert.equal(canon.podcastFeedRecords.length, 56);
  assert.match(canon.podcastAudit.feedUrl, /anchor\.fm\/s\/10a245f8\/podcast\/rss/);
  assert.equal(canon.stats.episodes, 102);
  assert.equal(canon.stats.movieGroups, 91);
  assert.equal(canon.stats.franchises, 13);
  assert.equal(canon.stats.deepDossiers, 38);
  assert.equal(canon.stats.captionLedgers, 63);
  assert.equal(canon.stats.sourceBriefs, 1);
  assert.equal(canon.stats.nonFullAdditions, 64);
  assert.equal(canon.stats.podcastOnlyCommentaries, 6);
  assert.equal(canon.stats.podcastFeedRecords, 56);
  assert.equal(canon.stats.uniqueFilmSources, 108);
  assert.equal(canon.stats.companionWatchalongs, 11);
  assert.equal(canon.stats.companionReviews, 17);
  assert.equal(canon.companionWatchalongs.length, 11);
  assert.equal(canon.companionReviews.length, 17);
  assert.ok(canon.companionWatchalongs.some((record) => /DUNKIRK/i.test(record.title)));
  assert.ok(canon.companionWatchalongs.some((record) => /Star Trek/i.test(record.title)));
  assert.ok(canon.companionReviews.some((record) => /LONGLEGS/i.test(record.title)));
  assert.equal(canon.podcastCommentaries.length, 6);
  assert.ok(canon.podcastCommentaries.some((record) => record.movieTitle === "Wayne's World"));
  assert.ok(canon.podcastCommentaries.some((record) => record.movieTitle === "Predator (1987)"));
  assert.ok(canon.podcastCommentaries.every((record) => record.status === "recovered-audio-lead" && record.evidence.publicPlayback === true));
  assert.equal(Object.keys(podcastAudio.records).length, 6);
  assert.ok(Object.values(podcastAudio.records).every((record) => record.status === "podcast-audio-feature" && record.candidates.length >= 20));
  assert.ok(Object.values(podcastAudio.records).every((record) => record.media.canonicalTimestampMapping === false));
  assert.ok(Object.values(podcastAudio.records).every((record) => record.dossier && record.dossier.chapters.length >= 3));
  assert.ok(Object.values(podcastAudio.records).some((record) => record.dossier.topics.length > 0));
  assert.equal(canon.stats.sourceCounts.heldMembersOnly, 22);
  assert.equal(canon.stats.sourceCounts.liveStrictCandidates, 112);
  assert.equal(canon.stats.sourceCounts.liveStrictPublicCandidates, 90);
  assert.equal(canon.stats.sourceCounts.legacyCatalogRetained, 12);
  assert.equal(canon.scope.channelSnapshotSources, 2882);
  assert.equal(canon.discovery.explicitCandidateCount, 112);
  assert.equal(canon.discovery.liveStrictCandidateCount, 112);
  assert.equal(canon.discovery.liveStrictPublicCandidateCount, 90);
  assert.equal(canon.discovery.liveStrictHeldCandidateCount, 22);
  assert.equal(canon.discovery.legacyCatalogRetained.length, 12);
  assert.equal(canon.discovery.broadCandidateCount, 139);
  assert.equal(canon.discovery.broadSignalCounts["watchalong-or-commentary"], 102);
  assert.equal(canon.discovery.broadSignalCounts["watchalong-edit"], 20);
  assert.equal(canon.discovery.broadDiscoveryOmissions.length, 49);
  assert.equal(canon.discovery.broadDiscoveryOmissions.filter((record) => record.availability === "subscriber_only").length, 24);
  assert.equal(canon.coverageLedger.publicYoutubeCanon, 102);
  assert.equal(canon.coverageLedger.podcastFeedRecords, 56);
  assert.equal(canon.coverageLedger.podcastFeedOverlaps, 50);
  assert.equal(canon.coverageLedger.uniqueFilmSources, 108);
  assert.equal(canon.discovery.edgeReview.publicEdgeLeads, 25);
  assert.equal(canon.discovery.edgeReview.captionConfirmed, 5);
  assert.equal(canon.coverageLedger.podcastRecoveries, 6);
  assert.equal(canon.coverageLedger.heldStrictMembersOnly, 22);
  assert.equal(canon.coverageLedger.adjacentPublicLeads, 25);
  assert.equal(canon.coverageLedger.unresolvedEdgeLeads, 0);
  assert.equal(canon.coverageLedger.companionWatchalongs, 11);
  assert.equal(canon.coverageLedger.companionReviews, 17);
  assert.equal(canon.coverageLedger.companionPublic, 25);
  assert.equal(canon.coverageLedger.companionHeld, 3);
  assert.ok(canon.coverageLedger.crossGenreExamples.some((record) => /Rambo/i.test(record.title)));
  assert.ok(canon.coverageLedger.crossGenreExamples.some((record) => /Wayne's World/i.test(record.title)));
  assert.ok(canon.discovery.broadDiscoveryOmissions.some((record) => /Watching GHOSTBUSTERS/i.test(record.title)));
  assert.equal(canon.discovery.heldTitleCandidates.length, 22);
  assert.match(canon.discovery.watchedMoviePattern, /we\\s\+watched/i);
  assert.match(canon.discovery.letWatchMoviePattern, /let/i);
  assert.equal(canon.episodes.find((episode) => episode.id === "9Kql8Y14bAw")?.movieTitle, "Sinister (2012)");
  assert.equal(canon.episodes.find((episode) => episode.id === "0X8Jq7wxfJo")?.movieTitle, "The Batman (2022)");
  assert.equal(canon.episodes.find((episode) => episode.id === "ot91NhcRSdM")?.movieTitle, "Child's Play (1988)");
  assert.equal(canon.episodes.find((episode) => episode.id === "BqIiHSqSM_U")?.movieTitle, "Candyman (1992)");
  assert.equal(canon.episodes.find((episode) => episode.id === "NZprZ1gWBIw")?.movieTitle, "Halloween (2018)");
  assert.ok(canon.discovery.titleCandidates.some((record) => /Rambo|Saved By The Bell|Batman|Terminator|Men In Black/i.test(record.title)));
  assert.equal(new Set(canon.episodes.map((episode) => episode.id)).size, canon.episodes.length);
  assert.match(watchPass.version, /^2026-audio-pilot-0[34]$/);
  assert.equal(watchPass.coverage.watchalongEpisodes, 102);
  assert.equal(watchPass.coverage.audioAnalyzed, 101);
  assert.equal(watchPass.coverage.held, 1);
  assert.equal(watchPass.coverage.alternateAudioAnalyzed, 1);
  assert.ok(watchPass.coverage.alternateRankedCandidates >= 30);
  assert.match(watchPass.selectionPolicy, /no fixed 48-card ceiling/i);
  assert.ok(watchPass.coverage.rankedCandidates >= 3000, "evidence-scaled watchalong routes expand beyond the former fixed shelf");
  assert.equal(canon.watchPassCoverage.audioAnalyzed, 101);
  const latestPilot = watchPass.episodes.LV2rmwEA0w4;
  assert.ok(latestPilot.audit.candidateCategories["STRAIGHT TO STEVE'S ASSHOLE"] > 0 || latestPilot.audit.candidateCategories["CHARACTER SIGNAL"] > 0, "current-show route selection preserves a recurring WWAM lane");
});

test("repeated films stay separate while grouping into one movie file", () => {
  const halloweenFour = canon.groups.find((group) => group.key === "halloween-4");
  const finalChapter = canon.groups.find((group) => group.key === "friday-the-13th-part-4");
  const halloweenOriginal = canon.groups.find((group) => group.key === "halloween-1978");
  const darkKnight = canon.episodes.find((episode) => episode.id === "NuGQKLkam_U");
  assert.deepEqual(Array.from(halloweenFour.episodeIds), ["28PfRNKoSCA", "KrBhfGxsJNM"]);
  assert.deepEqual(Array.from(finalChapter.episodeIds), ["kTJXSHz9BXw", "QxJyVaAgZ_Y"]);
  assert.deepEqual(Array.from(halloweenOriginal.episodeIds), ["6VXSBDZ-3WE", "NjH2tcGvmAY"]);
  assert.equal(halloweenFour.repeatCount, 1);
  assert.equal(finalChapter.repeatCount, 1);
  assert.equal(halloweenOriginal.repeatCount, 1);
  assert.equal(darkKnight.franchiseKey, "dc");
  assert.equal(canon.episodes.find((episode) => episode.id === "LHK_KKVd8nw")?.franchiseKey, "comedy", "Freddy Got Fingered is not misfiled as Nightmare on Elm Street");
  assert.equal(canon.episodes.find((episode) => episode.id === "wZqgaLkMq0U")?.topics.length, 0, "one-off caption topic noise is not promoted as a Saved by the Bell subject");
  assert.equal(canon.episodes.find((episode) => episode.id === "K9qwSM4Eqyw")?.topics.length, 0, "one-off caption topic noise is not promoted as a From Dusk Till Dawn subject");
});

test("every episode has an official source, evidence state, and playable receipt lane", () => {
  canon.episodes.forEach((episode) => {
    assert.match(episode.id, /^[A-Za-z0-9_-]{11}$/);
    assert.match(episode.url, new RegExp(episode.id));
    assert.ok(["full-editorial-dossier", "source-brief-dossier", "caption-ledger-dossier"].includes(episode.dossier.state));
    assert.ok(Array.isArray(episode.dossier.cuts));
    assert.ok(episode.dossier.summary.length > 30);
  });
  const halloweenParty = canon.episodes.find((episode) => episode.id === "KrBhfGxsJNM");
  assert.equal(halloweenParty.type, "watch-party");
  assert.equal(halloweenParty.movieKey, "halloween-4");
  assert.ok(halloweenParty.dossier.cuts.length >= 10);
  assert.ok(canon.stats.fanSignalReceipts >= 10);
  assert.ok(canon.episodes.some((episode) => episode.dossier.fanSignals.length > 0));
  const heldSource = canon.episodes.find((episode) => episode.id === "AzrcgoyE7C4");
  assert.equal(heldSource.dossier.state, "source-brief-dossier");
  assert.match(heldSource.dossier.summary, /source brief/i);
  const halloween = canon.episodes.filter((episode) => episode.franchiseKey === "halloween");
  assert.equal(halloween.length, 17);
  assert.ok(halloween.every((episode) => episode.watchPass), "every Halloween source has a watch-pass record");
  assert.ok(halloween.filter((episode) => episode.watchPass.status === "audio-feature-pilot").every((episode) => episode.watchPass.candidates.length >= 12), "acquired Halloween audio keeps a ranked route");
  assert.equal(heldSource.watchPass.status, "held-age-restricted");
  assert.equal(heldSource.watchPass.candidates.length, 0);
  assert.equal(heldSource.watchPass.alternateAudio.status, "alternate-audio-feature-pilot");
  assert.ok(heldSource.watchPass.alternateAudio.candidates.length >= 30);
  assert.equal(heldSource.watchPass.alternateAudio.alignment.exactTimestampMappingEstablished, false);
  assert.match(heldSource.watchPass.note, /duration drift/i);
  const recoveredSource = canon.episodes.find((episode) => episode.id === "tGsSV60FmX0");
  assert.equal(recoveredSource.dossier.state, "caption-ledger-dossier");
  assert.equal(recoveredSource.watchPass.status, "audio-feature-pilot");
  assert.ok(recoveredSource.watchPass.candidates.length >= 15);
  assert.ok(canon.episodes.every((episode) => episode.watchPass), "every watchalong source has a watch-pass record");
  assert.ok(canon.episodes.filter((episode) => episode.watchPass.status === "audio-feature-pilot").every((episode) => episode.watchPass.media.sourceUrl.includes(episode.id)));
  assert.ok(canon.episodes.some((episode) => episode.watchPass.label === "WATCHALONG WATCH PASS // AUDIO PILOT"));
  assert.ok(canon.episodes.some((episode) => episode.id === "ot91NhcRSdM" && episode.watchPass.status === "audio-feature-pilot"), "newly discovered highlight cuts receive a source-local ASR/audio route");
  const signs = canon.episodes.find((episode) => episode.id === "F1DTb9zwceY");
  assert.equal(signs.dossier.caption.sourceKind, "local-whisper-transcript");
  assert.equal(signs.watchPass.status, "audio-feature-pilot");
  assert.ok(signs.watchPass.candidates.length >= 20, "public no-caption source receives an audio/ASR route");
  assert.ok(canon.episodes.some((episode) => episode.watchPass.audit.candidateTarget > 15), "longer watchalongs receive a larger ranked browse set");
  assert.ok(canon.episodes.some((episode) => episode.watchPass.audit.candidateTarget > 48), "dense long tapes exceed the former 48-card ceiling");
  assert.ok(canon.episodes.filter((episode) => episode.duration >= 5400 && episode.watchPass.status === "audio-feature-pilot").every((episode) => episode.watchPass.candidates.length >= 15), "feature-length watchalongs retain at least fifteen audio-ranked routes");
  assert.ok(canon.episodes.filter((episode) => episode.dossier.state === "caption-ledger-dossier").every((episode) => !/local caption ledger leaves|indexed doors hit|cleanest way in|jumpable guide to the room/i.test(episode.dossier.summary)), "caption-ledger recaps do not fall back to the old machine-shaped boilerplate");
  const heldHalloweenTwo = canon.episodes.find((episode) => episode.id === "AzrcgoyE7C4");
  assert.match(heldHalloweenTwo.dossier.summary, /official podcast variant contributes \d+ audio-bound routes/i);
  assert.equal(canon.episodes.filter((episode) => !/^held-/.test(episode.watchPass.status)).filter((episode) => episode.watchPass.listeningDigest?.headline).length, 101, "every acquired watchalong has a listening read");
  const audioEnriched = canon.episodes.filter((episode) => /audio-feature pass adds/i.test(episode.dossier.summary));
  const audioCuts = audioEnriched.flatMap((episode) => episode.dossier.cuts.filter((cut) => cut.audio));
  assert.ok(audioEnriched.length >= 50, "caption-ledger watchalongs expose their audio-ranked routes in the show dossier");
  assert.ok(audioCuts.length >= 1000, "audio-ranked watchalong routes remain available as bounded dossier receipts");
  assert.ok(audioCuts.every((cut) => /audio \+ source-local caption alignment/i.test(cut.evidenceBasis) && cut.audioRank > 0), "audio dossier receipts retain their evidence boundary and rank");
  const audioBacked = canon.episodes.filter((episode) => episode.watchPass.status === "audio-feature-pilot");
  const allAudioDossierCuts = audioBacked.flatMap((episode) => episode.dossier.cuts.filter((cut) => cut.audio));
  assert.equal(audioBacked.length, 101, "every acoustically acquired watchalong retains an audio-feature route");
  assert.equal(canon.episodes.filter((episode) => episode.watchPass.status === "caption-ledger-pilot").length, 0, "caption-only fallback is empty when every acquired transcript has a matching audio route");
  assert.ok(allAudioDossierCuts.length >= 2000, "audio-ranked routes are also carried into full editorial dossiers");
  assert.equal(canon.episodes.filter((episode) => episode.dossier.state === "full-editorial-dossier" && episode.dossier.cuts.some((cut) => cut.audio)).length, 38, "all full editorial watchalong dossiers expose their audio-ranked routes");
  assert.ok(allAudioDossierCuts.every((cut) => cut.excerpt && !/[\\[]\\s*(?:__+|music|laughter|inaudible|bleep)\\s*[\\]]/i.test(cut.excerpt)), "audio dossier excerpts remove caption-stage marker debris and expose an honest fallback when no caption aligns");
  canon.episodes.forEach((episode) => {
    const audio = episode.dossier.cuts.filter((cut) => cut.audio).sort((left, right) => left.t - right.t);
    for (let index = 1; index < audio.length; index += 1) assert.ok(audio[index].t - audio[index - 1].t >= 18, `${episode.id} audio routes do not stack duplicate windows`);
  });
});

test("watchalong canon is reachable from the Watchalongs route", () => {
  assert.match(html, /id="watchalong-canon"/);
  assert.match(html, /href="#watchalong-canon"/);
  assert.match(html, /wwam-watchalong-canon\.js/);
  assert.match(html, /watchalong-canon\.css/);
  assert.match(html, /136 MOVIE-ROOM RECEIPTS \/\/ 102 FULL-FILM SOURCES \/\/ \+6 PODCASTS \/\/ \+11 COMPANION CUTS \/\/ \+17 REVIEWS \/ REACTIONS/);
  assert.match(html, /509 livestreams.*102 YouTube watchalong canon sources.*90 current public leads.*12 legacy records.*\+6 official podcast recoveries/i);
  assert.match(html, /509 current-canon livestreams.*108 indexed full-film sources/i);
  assert.doesNotMatch(html, /PUBLIC WATCHALONG CANON \/\/ 50 SOURCES \/ 47 MOVIE FILES/);
  assert.doesNotMatch(html, /131 livestreams|50 public watchalong sources/i);
  assert.match(html, /THIRTEEN FRANCHISE WORLDS \/\/ NINETY-ONE SOURCES/);
  assert.match(ui, /MOVIE FILES \/\/ REPEATS STAY ATTACHED/);
  assert.match(ui, /data-wac-group/);
  assert.match(ui, /function fanSignalsMarkup\(episode, signals\)/);
  assert.match(ui, /fanSignalsMarkup\(episode, dossier\.fanSignals\)/);
  assert.match(ui, /function watchPassMarkup\(episode\)/);
  assert.match(ui, /function alternateAudioMarkup\(pass\)/);
  assert.match(ui, /watchCandidateLabel/);
  assert.match(ui, /AUDIO FEATURE RANK/);
  assert.match(ui, /ACOUSTIC ONLY/);
  assert.match(ui, /function edgeAuditMarkup\(\)/);
  assert.match(ui, /function coverageLedgerMarkup\(\)/);
  assert.match(ui, /function companionShelfMarkup\(\)/);
  assert.match(ui, /THE OTHER MOVIE ROOMS/);
  assert.match(ui, /companionWatchalongs/);
  assert.match(ui, /MORE THAN 50\. THE AUDIT SAYS HOW MANY/);
  assert.match(ui, /YOUTUBE WATCHALONG CANON/);
  assert.match(ui, /RSS COMMENTARY RECEIPTS/);
  assert.match(ui, /THE OVERLOOKED EDGE/);
  assert.match(ui, /edgeReview/);
  assert.match(ui, /function keepPublicEdgeLinksLocal\(\)/, "public edge leads stay in the local app route");
  assert.match(ui, /function keepLocalReceiptLinks\(\)/, "bounded watchalong receipts stay in the local Show Wiki route");
  assert.match(ui, /a\[href\^=\\"\?source=/, "local receipt cleanup covers dossier links");
  assert.match(ui, /\.wac-edge-shelf a\[href\^=\\"\?source=/, "the local edge selector is scoped to the adjacent shelf");
  assert.match(ui, /link\.removeAttribute\("target"\)/, "public edge leads do not open a second tab");
  assert.match(ui, /function podcastRecoveryMarkup\(\)/);
  assert.match(ui, /OFFICIAL FEED RECOVERY/);
  assert.match(ui, /<audio id=.*controls/);
  assert.match(ui, /data-wac-podcast-seek/);
  assert.match(ui, /TAPE SHAPE \/\/ SOURCE-LOCAL READ/);
  assert.match(html, /wwam-podcast-commentary-audio\.js/);
  assert.match(ui, /broadDiscoveryOmissions/);
  assert.match(ui, /LISTENING READ \/\/ EVIDENCE MIX/);
  assert.match(ui, /AUDIO PASS/);
  assert.match(ui, /HALLOWEEN WATCH PASS/);
  assert.match(ui, /LISTEN FOR THE ROOM TO CHANGE/);
  assert.match(css, /\.wac-watch-pass/);
  assert.match(css, /\.wac-watch-pass-read/);
  assert.match(css, /\.wac-edge-shelf/);
  assert.match(css, /\.wac-companion-shelf/);
  assert.match(css, /\.wac-coverage-ledger/);
  assert.match(css, /\.wac-podcast-recovery/);
  assert.match(css, /\.wac-podcast-moment/);
  assert.match(css, /\.wac-podcast-shape/);
  assert.match(app, /OFFICIAL WWAM PODCAST VARIANT/);
  assert.match(app, /SEPARATE PODCAST CLOCK/);
  assert.match(app, /data-alternate-jump/);
  assert.match(dossierCss, /\.source-dossier-fallback-variant/);
  assert.match(dossierCss, /\.source-dossier-fallback-variant-grid/);
});
