import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const demo = path.join(root, "public", "demo");
const html = fs.readFileSync(path.join(demo, "index.html"), "utf8");
const ui = fs.readFileSync(path.join(demo, "watchalong-canon-ui.js"), "utf8");
const css = fs.readFileSync(path.join(demo, "watchalong-canon.css"), "utf8");
const context = { console };
context.window = context;
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(demo, "wwam-watchalong-canon.js"), "utf8"), context);
vm.runInContext(fs.readFileSync(path.join(demo, "wwam-watch-pass-pilot.js"), "utf8"), context);
const canon = context.WWAM_WATCHALONG_CANON;
const watchPass = context.WWAM_WATCH_PASS_PILOT;

test("watchalong canon has the complete public source registry", () => {
  assert.equal(canon.schema, "shokker-wwam-watchalong-canon/v1");
  assert.equal(canon.stats.episodes, 91);
  assert.equal(canon.stats.movieGroups, 88);
  assert.equal(canon.stats.franchises, 12);
  assert.equal(canon.stats.deepDossiers, 38);
  assert.equal(canon.stats.captionLedgers, 52);
  assert.equal(canon.stats.sourceBriefs, 1);
  assert.equal(canon.stats.nonFullAdditions, 53);
  assert.equal(canon.stats.sourceCounts.heldMembersOnly, 22);
  assert.equal(canon.scope.channelSnapshotSources, 2882);
  assert.equal(canon.discovery.explicitCandidateCount, 101);
  assert.equal(canon.discovery.broadCandidateCount, 110);
  assert.equal(canon.discovery.broadSignalCounts["watchalong-or-commentary"], 102);
  assert.equal(canon.discovery.broadDiscoveryOmissions.length, 31);
  assert.equal(canon.discovery.broadDiscoveryOmissions.filter((record) => record.availability === "subscriber_only").length, 24);
  assert.ok(canon.discovery.broadDiscoveryOmissions.some((record) => /Watching GHOSTBUSTERS/i.test(record.title)));
  assert.equal(canon.discovery.heldTitleCandidates.length, 22);
  assert.ok(canon.discovery.titleCandidates.some((record) => /Rambo|Saved By The Bell|Batman|Terminator|Men In Black/i.test(record.title)));
  assert.equal(new Set(canon.episodes.map((episode) => episode.id)).size, canon.episodes.length);
  assert.match(watchPass.version, /^2026-audio-pilot-0[34]$/);
  assert.equal(watchPass.coverage.watchalongEpisodes, 91);
  assert.equal(watchPass.coverage.audioAnalyzed, 90);
  assert.equal(watchPass.coverage.held, 1);
  assert.ok(watchPass.coverage.rankedCandidates >= 2000);
  assert.equal(canon.watchPassCoverage.audioAnalyzed, 90);
  const latestPilot = watchPass.episodes.LV2rmwEA0w4;
  assert.ok(latestPilot.audit.candidateCategories["STRAIGHT TO STEVE'S ASSHOLE"] > 0 || latestPilot.audit.candidateCategories["CHARACTER SIGNAL"] > 0, "current-show route selection preserves a recurring WWAM lane");
});

test("repeated films stay separate while grouping into one movie file", () => {
  const halloweenFour = canon.groups.find((group) => group.key === "halloween-4");
  const finalChapter = canon.groups.find((group) => group.key === "friday-the-13th-part-4");
  const halloweenOriginal = canon.groups.find((group) => group.key === "halloween-1978");
  const darkKnight = canon.episodes.find((episode) => episode.id === "NuGQKLkam_U");
  assert.deepEqual(Array.from(halloweenFour.episodeIds), ["28PfRNKoSCA", "KrBhfGxsJNM"]);
  assert.deepEqual(Array.from(finalChapter.episodeIds), ["kTJXSHz9BXw", "QxJyVaAgZ_Y"]);
  assert.deepEqual(Array.from(halloweenOriginal.episodeIds), ["6VXSBDZ-3WE", "NjH2tcGvmAY"]);
  assert.equal(halloweenFour.repeatCount, 1);
  assert.equal(finalChapter.repeatCount, 1);
  assert.equal(halloweenOriginal.repeatCount, 1);
  assert.equal(darkKnight.franchiseKey, "dc");
});

test("every episode has an official source, evidence state, and playable receipt lane", () => {
  canon.episodes.forEach((episode) => {
    assert.match(episode.id, /^[A-Za-z0-9_-]{11}$/);
    assert.match(episode.url, new RegExp(episode.id));
    assert.ok(["full-editorial-dossier", "source-brief-dossier", "caption-ledger-dossier"].includes(episode.dossier.state));
    assert.ok(Array.isArray(episode.dossier.cuts));
    assert.ok(episode.dossier.summary.length > 30);
  });
  const halloweenParty = canon.episodes.find((episode) => episode.id === "KrBhfGxsJNM");
  assert.equal(halloweenParty.type, "watch-party");
  assert.equal(halloweenParty.movieKey, "halloween-4");
  assert.ok(halloweenParty.dossier.cuts.length >= 10);
  assert.ok(canon.stats.fanSignalReceipts >= 10);
  assert.ok(canon.episodes.some((episode) => episode.dossier.fanSignals.length > 0));
  const heldSource = canon.episodes.find((episode) => episode.id === "AzrcgoyE7C4");
  assert.equal(heldSource.dossier.state, "source-brief-dossier");
  assert.match(heldSource.dossier.summary, /source brief/i);
  const halloween = canon.episodes.filter((episode) => episode.franchiseKey === "halloween");
  assert.equal(halloween.length, 16);
  assert.ok(halloween.every((episode) => episode.watchPass), "every Halloween source has a watch-pass record");
  assert.ok(halloween.filter((episode) => episode.watchPass.status === "audio-feature-pilot").every((episode) => episode.watchPass.candidates.length >= 12), "acquired Halloween audio keeps a ranked route");
  assert.equal(heldSource.watchPass.status, "held-age-restricted");
  assert.equal(heldSource.watchPass.candidates.length, 0);
  assert.match(heldSource.watchPass.note, /duration drift/i);
  assert.ok(canon.episodes.every((episode) => episode.watchPass), "every watchalong source has a watch-pass record");
  assert.ok(canon.episodes.filter((episode) => episode.watchPass.status === "audio-feature-pilot").every((episode) => episode.watchPass.media.sourceUrl.includes(episode.id)));
  assert.ok(canon.episodes.some((episode) => episode.watchPass.label === "WATCHALONG WATCH PASS // AUDIO PILOT"));
  assert.ok(canon.episodes.some((episode) => episode.watchPass.status === "caption-ledger-pilot"), "public caption-backed tapes retain a caption-only route when audio is unavailable");
  const signs = canon.episodes.find((episode) => episode.id === "F1DTb9zwceY");
  assert.equal(signs.dossier.caption.sourceKind, "local-whisper-transcript");
  assert.equal(signs.watchPass.status, "audio-feature-pilot");
  assert.ok(signs.watchPass.candidates.length >= 20, "public no-caption source receives an audio/ASR route");
  assert.ok(canon.episodes.some((episode) => episode.watchPass.audit.candidateTarget > 15), "longer watchalongs receive a larger ranked browse set");
  assert.equal(canon.episodes.filter((episode) => !/^held-/.test(episode.watchPass.status)).filter((episode) => episode.watchPass.listeningDigest?.headline).length, 90, "every acquired watchalong has a listening read");
  assert.ok(canon.episodes.filter((episode) => episode.watchPass.status === "caption-ledger-pilot").every((episode) => episode.watchPass.listeningDigest?.mode === "caption-only"), "caption-only tapes disclose their evidence mode");
  const audioEnriched = canon.episodes.filter((episode) => /audio-feature pass adds/i.test(episode.dossier.summary));
  const audioCuts = audioEnriched.flatMap((episode) => episode.dossier.cuts.filter((cut) => cut.audio));
  assert.ok(audioEnriched.length >= 50, "caption-ledger watchalongs expose their audio-ranked routes in the show dossier");
  assert.ok(audioCuts.length >= 1000, "audio-ranked watchalong routes remain available as bounded dossier receipts");
  assert.ok(audioCuts.every((cut) => /audio \+ source-local caption alignment/i.test(cut.evidenceBasis) && cut.audioRank > 0), "audio dossier receipts retain their evidence boundary and rank");
});

test("watchalong canon is reachable from the Watchalongs route", () => {
  assert.match(html, /id="watchalong-canon"/);
  assert.match(html, /href="#watchalong-canon"/);
  assert.match(html, /wwam-watchalong-canon\.js/);
  assert.match(html, /watchalong-canon\.css/);
  assert.match(html, /PUBLIC WATCHALONG CANON \/\/ 91 SOURCES \/ 88 MOVIE FILES/);
  assert.doesNotMatch(html, /PUBLIC WATCHALONG CANON \/\/ 50 SOURCES \/ 47 MOVIE FILES/);
  assert.match(html, /TWELVE FRANCHISE WORLDS \/\/ NINETY-ONE SOURCES/);
  assert.match(ui, /MOVIE FILES \/\/ REPEATS STAY ATTACHED/);
  assert.match(ui, /data-wac-group/);
  assert.match(ui, /function fanSignalsMarkup\(episode, signals\)/);
  assert.match(ui, /fanSignalsMarkup\(episode, dossier\.fanSignals\)/);
  assert.match(ui, /function watchPassMarkup\(episode\)/);
  assert.match(ui, /watchCandidateLabel/);
  assert.match(ui, /AUDIO FEATURE RANK/);
  assert.match(ui, /function edgeAuditMarkup\(\)/);
  assert.match(ui, /THE OVERLOOKED EDGE/);
  assert.match(ui, /broadDiscoveryOmissions/);
  assert.match(ui, /LISTENING READ \/\/ EVIDENCE MIX/);
  assert.match(ui, /AUDIO PASS/);
  assert.match(ui, /HALLOWEEN WATCH PASS/);
  assert.match(ui, /LISTEN FOR THE ROOM TO CHANGE/);
  assert.match(css, /\.wac-watch-pass/);
  assert.match(css, /\.wac-watch-pass-read/);
  assert.match(css, /\.wac-edge-shelf/);
});
